#! /bin/sh

echo "Is it morning? Please answer yes or no?"

read timeofday

# 变量取值需要加上双引号，以防变量是个空字符串或者变量中存在空格
if [ "$timeofday" = "yes" ]
then
	echo "Good morning"
else
	echo "Good afternoon"
fi

exit 0
